# Generated by Django 3.0.8 on 2020-12-16 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(75)])),
                ('direccion', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100)])),
                ('telefono', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999, message='Ingrese un telefono valido'), django.core.validators.MinValueValidator(111111111, message='Ingrese un telefono valido')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
    ]
