# Generated by Django 3.0.8 on 2020-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
    ]
