# Generated by Django 3.0.8 on 2020-12-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_abierto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='abierto',
            new_name='activo',
        ),
    ]
