# Generated by Django 3.0.8 on 2020-12-16 17:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sis_gastronomico.pedidos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('medio_pago', models.CharField(max_length=100)),
                ('cuotas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comision', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='MedioPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('medio_pedido', models.CharField(max_length=100)),
                ('aumento', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(0, 'No Entregado'), (1, 'En Camino'), (2, 'Entregado'), (3, 'Cancelado')], default=0)),
                ('numero_pedido', models.SmallIntegerField(blank=True, default=sis_gastronomico.pedidos.models.calc_num_pedido, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('piso', models.CharField(blank=True, max_length=3, null=True)),
                ('departamento', models.CharField(blank=True, max_length=3, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.MedioPago')),
                ('medio_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.MedioPedido')),
                ('turno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='turnos.Turno')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.SmallIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
